### ISSUE TITLE
Questions about creating new bindings

### ISSUE THREAD

**Issue by malte-v** [godotengine/godot_headers#36]
I am planning to create GDNative/Nativescript bindings for the [Crystal language](https://crystal-lang.org/). I already had a look at some bindings for other langauges, and they all seem to generate their source files based on an api.json specification file provided by the engine executable itself. However, I still don't understand how those generated files are related to the Godot C headers. Apart from this, what other steps are required in order to make the bindings work?
Thanks in advance!

**Comment by BastiaanOlij** [comment]
@malte-v the api.json basically contains all the meta data for the different objects that make up the Godot game engine.

GDNative only gives you an API for calling into Godot. So you have an API call for things like:

- Instantiate object X
- Call method A on this instance
- Get property value for property B on this instance
- Destruct the instance
- Etc.

And you can just use it as is (many C based GDNative plugins are written like that). But it doesn't provide you any information about what objects there are available, what methods those objects have, what properties you can interact with. You as a programmer need to know exactly what is available and then call the right functions to perform the needed actions. Even something seemingly simple as a method call on an object becomes a fairly involved process where you have to pack your parameters into variants, add them to an array, pass that through, expand the variant you get returned, etc. It's not very developer friendly. 

The api.json file contains all the information about the objects available in a particular version of Godot (and likely for many versions to come afterwards) so you can generate binding code and present the developer with something that reflects the objects in a structure that makes sense for the language you're supporting.

**Comment by malte-v** [comment]
Thank you, that helped a lot!

**Comment by malte-v** [comment]
OK, so I managed to create binding code which allows me to call GDNative C functions from within my Crystal code. Crystal offers a handy syntax to do this, and with [libgen](https://github.com/olbat/libgen) I was able to generate all this copy-paste code from `gdnative_api_struct.gen.h` (I guess it contains all GDNative functions). You can have a look at it [here](https://hastebin.com/vacewenaro.rb). Of course the Crystal compiler needs to know where to find these functions, and therefore I need to specify linker flags that point to an object file.
Since I am a total n00b regarding C, I tried to compile the `gdnative_api_struct.gen.h` header and got a warning that said "unrecognized type of source file" and no object file. My cheap approach was to create a source file which contained nothing but `#include <gdnative_api_struct.gen.h>`. This compiled successfully, but obviously I ended up with an empty object file as I didn't use any of the functions.
I'm sorry if my question is dumb and doesn't belong here, but how to do I get an object file of the GDNative headers?

**Comment by sheepandshepherd** [comment]
You shouldn't link the functions at all -- that's normally how bindings to C libraries work, but GDNative works differently. Instead, your game's Crystal code will be compiled to a library and Godot will load it, so there's no objects to link.

What the bindings need is API structs containing function pointers -- in your case, `GodotGdnativeCoreApiStruct` and so on. Keep those, but delete the bare functions outside the structs. The API struct will be passed to your library when it's loaded, and all GDNative functions should be accessed through it.

Your library should export 3 C-ABI functions similar to this:  
```c
// called when your game library is loaded; options contains a pointer to the GodotGdnativeCoreApiStruct
void godot_gdnative_init(godot_gdnative_init_options* options)
{
    // store options.api_struct so it can be accessed by the rest of your bindings
}
// also called when loaded
void godot_nativescript_init(void* handle)
{
    // register all of the game's script classes with godot_nativescript_register_class, etc
}
void godot_gdnative_terminate(godot_gdnative_terminate_options* options)
{
}
```
The prefix on the function names can optionally be different from `godot_` if it's set in the GDNativeLibrary resource.

I don't know much about Crystal, but I read that it doesn't have dynamic libraries. If that's still the case, it might be difficult to integrate with Godot, at least the way GDNative is currently structured.

**Comment by maltevoos** [comment]
Sorry for reopening this again :-(
I finally found out how to create a DLL from Crystal code (https://github.com/maltevoos/crystal-dll-demo), so the bindings would work on all platforms. The reason why I'm trying so hard is Crystal's awesome macro system which would allow me to generate all the `register_xyz()` code at compile time (even conditionally, like when a class inherits from `Node`).
The [GDNative C Example](http://docs.godotengine.org/en/3.0/tutorials/plugins/gdnative/gdnative-c-example.html) article was very helpful for understanding the basics of GDNative. But there are some more questions that I couldn't find answers to:

1. GDNative has built-in memory management functions like `godot_string_new`, `godot_string_destroy`, ... However, I would like to be able to use normal Crystal strings where Godot strings are required (IIRC godot-nim also has this feature), but these Crystal strings are tracked by Crystal's garbage collector. So, who is responsible for memory management in general? The language runtime or GDNative?

2. In the C++ bindings, you can define your methods just like you would in GDScript (with named and typed arguments). In the C example, it looks like this: 
`godot_variant simple_get_data(godot_object *p_instance, void *p_method_data,
        void *p_user_data, int p_num_args, godot_variant **p_args)`
So how is the C++ member function with the named arguments registered to GDNative?

3. Do GDNative classes need to inherit from `Node` in order to serve as a script?

Thank you for your help!

**Comment by karroffel** [comment]
1) GDNative does not have any concept of garbage collection at all. When you create a `godot_string` then you have to manually destroy it again. If you want to use a crystal string, what you really want to do is use that crystal string to create the Godot string. That's how Rust does it and I think Nim as well.

    ```crystal
    def do_something(str)
        gdstr = godot_string.new_from_utf8(str.to_utf8())
        use_godot_string(gdstr)
    end
    ```

    (I don't know crystal very well, so please excuse my horrible pseudo code)

2) The C++ bindings cheat a lot using a lot of templates.
    
    Basically when have a function `void f(int a, float b)` it creates an intermediate structure using templates like this

    ```cpp
    struct Method {
        void (*YourClass::function)(int, float);
        static godot_variant apply(godot_object *p_instance, void *p_method, void *user, int num, godot_variant **args) {
            Method *m = (Method *) p_method;
            YourClass *obj = (YourClass *) user;
            int a = cast_thing(args[0]);
            float b = cast_thing(args[1]);
            (obj->(m->function))(a, b);
            return null_variant;
        }
    }
    ```

    (Mostly pseudo code again, I can't remember all this weird C++ syntax etc, but that's the general idea)

3) No, any class that inherits from `Object` can be attached to an object, but `Node`s are the most common, together with `Reference`s. There's other ways you can use GDNative, but "NativeScript" is the one you usually want.

**Comment by maltevoos** [comment]
OK, so I managed to create a test project with Crystal bindings that compiles fine (at least on my windows machine): https://github.com/maltevoos/crodot. Basically, I followed the instructions in the GDNative C example but translated everything to Crystal. The problem I have now is that when the library is loaded through GDScript, the game crashes after the splash screen and the following error message gets printed out:
`drivers/windows/stream_peer_tcp_winsock.cpp:203 - Server disconnected!`
It got even worse when I closed and reopened the editor. Now, the editor crashes whenever my library is referenced anywhere in the project.
I checked if the init/terminate functions are properly exported from the DLL, and yes, they are. Unfortunately that's all I could do so far since I have zero debug information apart from the error message above. Do you have an idea what could cause this? I appreciate your time!

---

Short explanation of the test project:
- src/godot.cr: declarations of the GDNative structs
- src/library.cr: entry point to Crystal
- crodot/wrapper.c: C wrapper around Crystal code that allows builing shared libraries; the actual entry point for Godot
- bin/: here are the binaries and the GDNLIB/GDNS files

**Comment by malte-v** [comment]
I've put my project on hold because I was quite busy lately, but now I was able to rewrite the GDNative C example in Crystal and run it without getting segfaults. However, I have a weird issue with it and I have no idea what it's caused by. I'll try to explain it as detailed as possible:
1. When opening the project, both `gdnative_init` and `nativescript_init` are called and the editor works fine.
2. When the editor loses and gains focus, both functions are called again (no idea why), still everything works fine.
3. When the editor gains focus the fourth time, everything freezes with no command line output. No function is called.
4. If I start the game via the play button before the editor has frozen, the game works as expected: Clicking the button causes a "Hello World from Crystal!" text to be displayed.

Project including GDNative binaries is here: https://github.com/malte-v/gdnative-crystal

Any idea what could cause this? Thank you for your time!

**Comment by sheepandshepherd** [comment]
Godot fully unloads the library when the editor window loses focus. This is to allow recompiling the library without closing the editor. Make sure you account for this with how the init/terminate functions and Crystal classes are designed.

Without knowing the language, I can only guess what specifically is causing the crash, but some possibilites:  
- are runtime library and garbage collector terminated properly when the library unloads?
- are scripts destroyed and deallocated properly? Godot will call the destructors you give it when registering the classes
- when the library is reloaded, are the scripts being constructed again and getting their properties set?
- properties are the *only* data that is restored to script instances after reload, so make sure there aren't non-exposed variables.

The best way to debug this is probably running Godot through GDB or something. I had many crashes like this, always with very different causes.

**Comment by malte-v** [comment]
Thanks for the advice. Running Godot through gdb revealed that there was some segfault deep inside the garbage collector, so I disabled it. Anyways, I was finally able to get the example up and running. Can I leave this issue open as some sort of Q&A thread for binding authors? It would be easier to find then.

**Comment by aaronfranke** [comment]
Issues on GitHub are not really the best place to receive tech support. If you still have questions, then that seems like a lack of documentation, in which case issues should be opened about adding missing documentation.
