### ISSUE TITLE
Adding new overloads for Vector3 (Vector2) nad one more constructor.

### ISSUE THREAD

**Issue by ligazetom** [godotengine/godot_headers#62]
I am working with Vector3 objects a lot right now and I see there is no overloaded operator for -= (real_t) and many others like this. Also, constructor which would initialize all coordinates to the same value could be nice.

I will definitely implement it in my version of godot-cpp. Just wanted to know if there is a reason why it is not already implemented.

**Comment by aaronfranke** [comment]
This would have to be added to the core API before it could be added to GDNative. If desired, open a proposal on the godot-proposals repository.

Note: Personally, I don't see a need for this, it isn't a super common use case, and in GDScript you can already use `Vector3.ONE * value` instead of `Vector3(value)`.
